# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lqMfLFDiEv0Q17yaSv8cyZmeM2BOkUT-
"""



from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Load the CSV file into a pandas DataFrame, specifying 'latin1' encoding
df = pd.read_csv('/content/Consolidado_Internacao_Poluicao.csv', encoding='latin1', sep=';')

# Display the first 5 rows of the DataFrame
display(df.head(18))

import matplotlib.pyplot as plt
import seaborn as sns

# Create a figure and a primary axes
fig, ax1 = plt.subplots(figsize=(12, 7))

# Plot Poluicao_Anual_Total on the primary y-axis (ax1)
sns.lineplot(x='Ano', y='Poluicao_Anual_Total', data=df, ax=ax1, color='blue', marker='o', label='Poluicao_Anual_Total')
ax1.set_xlabel('Ano', color='black', fontsize=12)
ax1.set_ylabel('Poluicao_Anual_Total', color='black', fontsize=12)
ax1.tick_params(axis='y', labelcolor='black')
ax1.tick_params(axis='x', labelcolor='black', labelsize=12)

# Create a second y-axis that shares the same x-axis
ax2 = ax1.twinx()

# Plot Internações por doenças respiratórias on the secondary y-axis (ax2)
sns.lineplot(x='Ano', y='Internações por doenças respiratórias', data=df, ax=ax2, color='red', marker='x', label='Internações por doenças respiratórias')
ax2.set_ylabel('Internações por doenças respiratórias', color='black', fontsize=12)
ax2.tick_params(axis='y', labelcolor='black')

plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(df['Ano'].unique(), rotation=45, ha='right')

# Add legend
lines, labels = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax2.legend(lines + lines2, labels + labels2, loc='upper left')

plt.tight_layout() # Adjust layout to prevent labels from being cut off
plt.show()

"""### Normalização dos Dados Anuais

Vamos normalizar as colunas numéricas `'Poluicao_Anual_Total'`, `'Internações por doenças do aparelho respiratório'`, `'Internações por doenças do trato respiratório superior'`, e `'Internações por doenças respiratórias'` usando a técnica de Min-Max Scaling. Esta técnica escala os valores para um intervalo entre 0 e 1, o que pode ser útil para comparações entre variáveis com diferentes escalas ou para algoritmos de machine learning.
"""

from sklearn.preprocessing import MinMaxScaler

# Identify columns to normalize
columns_to_normalize = [
    'Poluicao_Anual_Total',
    'Internações por doenças do aparelho respiratório',
    'Internações por doenças do trato respiratório superior',
    'Internações por doenças respiratórias'
]

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Apply Min-Max scaling to the selected columns
df_normalized = df.copy()
df_normalized[columns_to_normalize] = scaler.fit_transform(df[columns_to_normalize])

# Display the head of the DataFrame with normalized data
print("DataFrame com dados normalizados:")
display(df_normalized.head())

# Display descriptive statistics for normalized columns to verify
print("Estatísticas descritivas das colunas normalizadas:")
display(df_normalized[columns_to_normalize].describe())

"""### Definição das Variáveis (X e y) e Divisão da Base de Dados

Vamos definir nossa variável alvo (`y`) como `'Internações por doenças respiratórias'` e as variáveis preditoras (`X`) como todas as outras colunas relevantes do DataFrame normalizado, excluindo o `'Ano'` e a própria variável alvo.
"""

# Variável alvo (y)
y = df_normalized['Internações por doenças respiratórias']

# Variáveis preditoras (X): Todas as outras colunas relevantes, excluindo 'Ano' e a variável alvo
X = df_normalized.drop(columns=['Ano', 'Internações por doenças respiratórias', 'Unnamed: 0'])


print("Primeiras 5 linhas das variáveis preditoras (X):")
display(X.head())

print("Primeiras 5 linhas da variável alvo (y):")
display(y.head())

"""### Divisão da Base de Dados para Treinamento e Teste

Para avaliar o desempenho do nosso modelo de forma robusta, dividiremos os dados normalizados em conjuntos de treinamento e teste. Isso garante que o modelo seja treinado com uma parte dos dados e avaliado em dados que ele não viu durante o treinamento, fornecendo uma estimativa mais realista de sua capacidade de generalização.
"""

from sklearn.model_selection import train_test_split

# Dividir os dados em conjuntos de treinamento e teste
# Usaremos 80% para treinamento e 20% para teste, com um random_state para reprodutibilidade
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Shape de X_train: {X_train.shape}")
print(f"Shape de X_test: {X_test.shape}")
print(f"Shape de y_train: {y_train.shape}")
print(f"Shape de y_test: {y_test.shape}")

"""### Construção e Avaliação de Modelos Preditivos

Vamos agora construir e avaliar diferentes modelos de regressão para prever as 'Internações por doenças respiratórias'. Começaremos com o Random Forest Regressor, que é um algoritmo de ensemble robusto e amplamente utilizado.

#### 1. Random Forest Regressor

O Random Forest é um algoritmo versátil que pode ser usado para tarefas de classificação e regressão. Ele constrói múltiplas árvores de decisão e as une para obter uma previsão mais precisa e estável. Vamos treiná-lo com nossos dados e avaliar seu desempenho.
"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Inicializar e treinar o modelo Random Forest Regressor
rf_model = RandomForestRegressor(n_estimators=100, random_state=42) # n_estimators é o número de árvores na floresta
rf_model.fit(X_train, y_train)

# Fazer previsões no conjunto de teste
y_pred_rf = rf_model.predict(X_test)

# Avaliar o desempenho do modelo
mae_rf = mean_absolute_error(y_test, y_pred_rf)
mse_rf = mean_squared_error(y_test, y_pred_rf)
rmse_rf = mse_rf**0.5 # Root Mean Squared Error
r2_rf = r2_score(y_test, y_pred_rf)

print("Desempenho do Random Forest Regressor:")
print(f"MAE: {mae_rf:.4f}")
print(f"MSE: {mse_rf:.4f}")
print(f"RMSE: {rmse_rf:.4f}")
print(f"R-squared: {r2_rf:.4f}")

"""#### 2. Gradient Boosting Machine (GBM)

O Gradient Boosting é outro poderoso algoritmo de ensemble que constrói modelos sequencialmente, onde cada novo modelo tenta corrigir os erros dos modelos anteriores. Ele geralmente oferece alta precisão.
"""

from sklearn.ensemble import GradientBoostingRegressor

# Inicializar e treinar o modelo Gradient Boosting Regressor
gbm_model = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
gbm_model.fit(X_train, y_train)

# Fazer previsões no conjunto de teste
y_pred_gbm = gbm_model.predict(X_test)

# Avaliar o desempenho do modelo
mae_gbm = mean_absolute_error(y_test, y_pred_gbm)
mse_gbm = mean_squared_error(y_test, y_pred_gbm)
rmse_gbm = mse_gbm**0.5
r2_gbm = r2_score(y_test, y_pred_gbm)

print("Desempenho do Gradient Boosting Machine:")
print(f"MAE: {mae_gbm:.4f}")
print(f"MSE: {mse_gbm:.4f}")
print(f"RMSE: {rmse_gbm:.4f}")
print(f"R-squared: {r2_gbm:.4f}")

"""#### 3. Support Vector Regressor (SVR)

O Support Vector Regressor (SVR) é uma extensão das Support Vector Machines (SVMs) para problemas de regressão. Ele tenta encontrar uma função que desvie o mínimo possível dos dados de treinamento, mantendo a função o mais plana possível.
"""

from sklearn.svm import SVR

# Inicializar e treinar o modelo Support Vector Regressor
svr_model = SVR(kernel='rbf') # Usando o kernel RBF (Radial Basis Function)
svr_model.fit(X_train, y_train)

# Fazer previsões no conjunto de teste
y_pred_svr = svr_model.predict(X_test)

# Avaliar o desempenho do modelo
mae_svr = mean_absolute_error(y_test, y_pred_svr)
mse_svr = mean_squared_error(y_test, y_pred_svr)
rmse_svr = mse_svr**0.5
r2_svr = r2_score(y_test, y_pred_svr)

print("Desempenho do Support Vector Regressor:")
print(f"MAE: {mae_svr:.4f}")
print(f"MSE: {mse_svr:.4f}")
print(f"RMSE: {rmse_svr:.4f}")
print(f"R-squared: {r2_svr:.4f}")

"""### Comparativo dos Modelos

Para facilitar a visualização e decisão sobre qual modelo é o mais adequado, vamos comparar as métricas de desempenho de todos os modelos treinados em uma única tabela.
"""

import pandas as pd

# Criar um DataFrame para armazenar as métricas de cada modelo
model_performance = pd.DataFrame({
    'Modelo': ['Random Forest Regressor', 'Gradient Boosting Machine', 'Support Vector Regressor'],
    'MAE': [mae_rf, mae_gbm, mae_svr],
    'MSE': [mse_rf, mse_gbm, mse_svr],
    'RMSE': [rmse_rf, rmse_gbm, rmse_svr],
    'R-squared': [r2_rf, r2_gbm, r2_svr]
})

# Exibir a tabela de desempenho
print("Tabela Comparativa de Desempenho dos Modelos:")
display(model_performance.sort_values(by='R-squared', ascending=False))

"""#### Visualização da Comparação de R-squared

Para uma análise visual mais rápida, vamos plotar os valores de R-squared para cada modelo.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Plotar R-squared dos modelos
plt.figure(figsize=(10, 6))
sns.barplot(x='Modelo', y='R-squared', data=model_performance.sort_values(by='R-squared', ascending=False), palette='viridis')
plt.xlabel('Modelo')
plt.ylabel('R-squared')
plt.ylim(0, 1) # R-squared geralmente varia de 0 a 1
plt.xticks(rotation=0, ha='center')
plt.yticks()
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Previsão para Anos Futuros (2026 e 2027) e Margem de Confiança

Para realizar as previsões para os anos de 2026 e 2027, utilizaremos o modelo Gradient Boosting Machine (GBM), que se mostrou o mais eficaz. Como não temos dados futuros para todas as variáveis preditoras (poluição e outros tipos de internações), faremos as seguintes suposições:

**Suposições para as Variáveis Preditoras em 2026 e 2027:**

Para as variáveis `Poluicao_Anual_Total`, `Internações por doenças do aparelho respiratório`, e `Internações por doenças do trato respiratório superior`, que são as colunas de `X`, iremos assumir que elas permanecerão constantes nos seus **últimos valores normalizados observados** no nosso conjunto de dados original (`df_normalized`). Esta é uma simplificação comum na ausência de dados futuros ou de um modelo separado para prever essas variáveis. Essa abordagem pressupõe que as condições dessas variáveis não mudarão drasticamente nos próximos anos.

"""

import numpy as np

# Identificar os últimos valores normalizados das variáveis preditoras
# 'Internações por doenças respiratórias' é a variável alvo, então não a incluímos aqui.
last_normalized_values = df_normalized.drop(columns=['Ano', 'Internações por doenças respiratórias', 'Unnamed: 0']).iloc[-1]

# Criar um DataFrame para os anos futuros (2026 e 2027)
years_to_predict = pd.DataFrame({
    'Ano': [2026, 2027]
})

# Adicionar as colunas preditoras com os últimos valores normalizados assumidos
for col in last_normalized_values.index:
    years_to_predict[col] = last_normalized_values[col]

# Garantir que a ordem das colunas seja a mesma do X_train
X_future = years_to_predict[X_train.columns] # Seleciona apenas as colunas usadas para treino

print("Dados de entrada para as previsões de 2026 e 2027 (valores normalizados):")
display(X_future)

# Fazer previsões com o modelo GBM (que foi o melhor)
y_pred_future_normalized = gbm_model.predict(X_future)

# Para desnormalizar as previsões, precisamos usar o MinMaxScaler original.
# Lembre-se que 'scaler' foi ajustado para as 4 colunas originais:
# ['Poluicao_Anual_Total', 'Internações por doenças do aparelho respiratório',
#  'Internações por doenças do trato respiratório superior', 'Internações por doenças respiratórias']
# Precisamos 'recriar' um array com as outras 3 colunas em qualquer valor para usar inverse_transform.

# O scaler foi fitado em 'columns_to_normalize'
# 'Internações por doenças respiratórias' é a última coluna na lista original do scaler.

# Criar um array temporário com as 3 colunas de X_future e a previsão da 4ª coluna
# A ordem das colunas no scaler.data_range_ e scaler.data_min_ é a que importa.
# Precisamos descobrir a posição da coluna 'Internações por doenças respiratórias' na lista original 'columns_to_normalize'

# Encontrar a posição da coluna alvo na lista original de normalização
target_col_index = columns_to_normalize.index('Internações por doenças respiratórias')

# Criar um array para cada previsão, onde apenas a coluna alvo é a previsão
# As outras colunas precisam de valores, pode ser 0, pois inverse_transform ignorará esses valores
# quando aplicarmos a matriz correta de data_min_ e data_range_ do scaler.

# Para cada previsão, vamos criar um array 1x4 (ou 1xN onde N é o número de colunas normalizadas)
# e preencher a posição da variável alvo com a previsão normalizada.

y_pred_future_denormalized = []
for pred_norm in y_pred_future_normalized:
    temp_array = np.zeros((1, len(columns_to_normalize)))
    temp_array[0, target_col_index] = pred_norm
    # Aplicar inverse_transform ao array temporário
    denormalized_row = scaler.inverse_transform(temp_array)
    y_pred_future_denormalized.append(denormalized_row[0, target_col_index])

# Adicionar as previsões desnormalizadas ao DataFrame de anos futuros
years_to_predict['Internações por doenças respiratórias (Previsto)'] = y_pred_future_denormalized

print("Previsões desnormalizadas para 2026 e 2027:")
display(years_to_predict[['Ano', 'Internações por doenças respiratórias (Previsto)']])

"""### Análise das Previsões e Considerações sobre Margem de Confiança

As previsões acima para os anos de 2026 e 2027 indicam o número esperado de internações por doenças respiratórias, baseadas no modelo GBM e nas suposições feitas para as variáveis preditoras.

**Interpretação:**

*   Os valores previstos são em escala original, o que os torna mais fáceis de interpretar no contexto real.
*   É importante lembrar que estas previsões são **pontuais**, ou seja, representam o valor mais provável de acordo com o modelo e as premissas.

**Margem de Confiança:**

Calcular uma margem de confiança (ou intervalo de predição) para modelos de *Gradient Boosting* é mais complexo do que para modelos lineares tradicionais, pois GBMs não fornecem diretamente estimativas de variância para suas previsões.

Para obter uma estimativa de margem de confiança, abordagens comuns incluem:

1.  **Bootstrapping:** Treinar o modelo GBM várias vezes em subamostras com reposição dos dados de treinamento. As previsões para os anos futuros seriam então uma distribuição de valores, a partir da qual se poderia calcular um intervalo de confiança (e.g., 2.5% e 97.5% percentis).
2.  **Modelos que fornecem intervalos intrínsecos:** Utilizar modelos que são projetados para fornecer intervalos de predição, como *Quantile Regression Forests* ou métodos bayesianos.
3.  **Bibliotecas dedicadas:** Algumas bibliotecas (`MAPIE` no Python) fornecem métodos para construir intervalos de predição para modelos *black-box* como GBM.

**Limitações:**

As previsões apresentadas têm como base a premissa de que os padrões históricos continuarão e, crucialmente, que as variáveis preditoras (poluição e outros tipos de internações) permanecerão em seus últimos níveis observados. Qualquer mudança significativa nessas variáveis no futuro (e.g., políticas de controle de poluição, eventos de saúde pública) invalidaria essas suposições e, consequentemente, as previsões.

**Próximos Passos (Se desejado):**

*   Implementar o bootstrapping para calcular intervalos de confiança para essas previsões.
*   Explorar modelos com capacidade intrínseca de estimar incerteza.
*   Se houver dados ou projeções futuras para as variáveis preditoras, incorporá-las para previsões mais realistas.

### Calculando Margem de Confiança (95% CI) para as Previsões via Bootstrapping

Para estimar a margem de confiança das previsões do modelo GBM, utilizaremos a técnica de bootstrapping. Este método envolve o reamostragem (com reposição) dos dados de treinamento várias vezes, treinando um novo modelo GBM em cada amostra e fazendo previsões. A distribuição dessas previsões nos permite construir intervalos de confiança.
"""

from sklearn.utils import resample

# Número de iterações de bootstrapping
n_bootstraps = 1000

# Lista para armazenar as previsões bootstrapped para os anos futuros
bootstrapped_predictions_2026 = []
bootstrapped_predictions_2027 = []

# Obter o índice da coluna alvo para desnormalização
target_col_index = columns_to_normalize.index('Internações por doenças respiratórias')

# Loop de bootstrapping
for i in range(n_bootstraps):
    # Reamostrar os dados de treinamento com reposição
    X_sample, y_sample = resample(X_train, y_train, random_state=i)

    # Treinar um novo modelo GBM na amostra bootstrapped
    gbm_bootstrap_model = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
    gbm_bootstrap_model.fit(X_sample, y_sample)

    # Fazer previsões nos dados futuros (X_future)
    y_pred_future_normalized_bootstrap = gbm_bootstrap_model.predict(X_future)

    # Desnormalizar as previsões e armazenar
    # Para 2026
    temp_array_2026 = np.zeros((1, len(columns_to_normalize)))
    temp_array_2026[0, target_col_index] = y_pred_future_normalized_bootstrap[0]
    denormalized_2026 = scaler.inverse_transform(temp_array_2026)[0, target_col_index]
    bootstrapped_predictions_2026.append(denormalized_2026)

    # Para 2027
    temp_array_2027 = np.zeros((1, len(columns_to_normalize)))
    temp_array_2027[0, target_col_index] = y_pred_future_normalized_bootstrap[1]
    denormalized_2027 = scaler.inverse_transform(temp_array_2027)[0, target_col_index]
    bootstrapped_predictions_2027.append(denormalized_2027)

# Calcular os intervalos de confiança (2.5% e 97.5% percentis) para 95% CI
lower_bound_2026 = np.percentile(bootstrapped_predictions_2026, 2.5)
upper_bound_2026 = np.percentile(bootstrapped_predictions_2026, 97.5)

lower_bound_2027 = np.percentile(bootstrapped_predictions_2027, 2.5)
upper_bound_2027 = np.percentile(bootstrapped_predictions_2027, 97.5)

# Obter as previsões pontuais originais para exibir
prediction_2026 = years_to_predict['Internações por doenças respiratórias (Previsto)'].iloc[0]
prediction_2027 = years_to_predict['Internações por doenças respiratórias (Previsto)'].iloc[1]

print(f"Previsões para 2026 e 2027 (Internações por doenças respiratórias):")
print(f"2026: {prediction_2026:.0f}")
print(f"2027: {prediction_2027:.0f}")
print("")
print("Margem de Confiança (95% CI) para as Previsões:")
print("------------------------------------------------")
print(f"2026: {prediction_2026:.0f} (CI 95%: [{lower_bound_2026:.0f}, {upper_bound_2026:.0f}])")
print(f"2027: {prediction_2027:.0f} (CI 95%: [{lower_bound_2027:.0f}, {upper_bound_2027:.0f}])")

"""### Impressões Finais sobre o Comparativo dos Modelos

Aqui está um resumo das impressões sobre o desempenho de cada modelo, utilizando as métricas de RMSE, MAE e R-squared:

**Resumo Comparativo dos Modelos de Regressão:**
---------------------------------------------------
**Random Forest Regressor:**
  RMSE: 0.0621
  MAE: 0.0620
  R²: 0.9630

**Gradient Boosting Machine Regressor (GBM):**
  RMSE: 0.0430
  MAE: 0.0384
  R²: 0.9823

**Support Vector Regressor (SVR):**
  RMSE: 0.2125
  MAE: 0.1801
  R²: 0.5667

**Conclusão:**

O **Gradient Boosting Machine (GBM)** apresentou o melhor desempenho geral, com o menor RMSE e MAE e o maior R², indicando uma excelente capacidade de previsão. O Random Forest Regressor também obteve um bom resultado. O Support Vector Regressor (SVR) foi o modelo com o pior desempenho, sugerindo que não se adequa bem a este conjunto de dados para a tarefa de regressão.

### Visualização Temporal dos Dados Reais e Previsões do Modelo GBM

Para ter uma visão abrangente do desempenho do modelo e de suas previsões futuras, vamos criar um gráfico de linha que mostra os dados históricos reais, as previsões do GBM para o período histórico e as previsões estendidas para 2026 e 2027.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Create a combined dataframe for plotting the lines
# It will contain 'Ano', 'Internações Reais (Histórico)', and 'Previsão GBM (Histórico e Futuro)'
# 'Internações Reais (Histórico)' will be NaN for future years
df_plot = pd.merge(df_real_historical, df_all_gbm_predictions, on='Ano', how='outer')

# Rename columns for clear labels in the plot
df_plot.rename(columns={
    'Real': 'Internações Reais (Histórico)',
    'Previsão GBM': 'Previsão GBM (Histórico e Futuro)'
}, inplace=True)

df_plot = df_plot.sort_values(by='Ano').reset_index(drop=True)

# Extract future prediction values and their corresponding years for error bars
predictions_future_original_scale = years_to_predict['Internações por doenças respiratórias (Previsto)'].values
future_years_for_errorbar = ci_plot_data['Ano'].values # [2026, 2027]

# Calculate the margin of error for the confidence intervals
# yerr in errorbar takes half the total length of the error bar
margin_of_error_original_scale = np.array([
    (ci_plot_data.loc[ci_plot_data['Ano'] == 2026, 'upper_bound'].iloc[0] - ci_plot_data.loc[ci_plot_data['Ano'] == 2026, 'lower_bound'].iloc[0]) / 2,
    (ci_plot_data.loc[ci_plot_data['Ano'] == 2027, 'upper_bound'].iloc[0] - ci_plot_data.loc[ci_plot_data['Ano'] == 2027, 'lower_bound'].iloc[0]) / 2
])

plt.figure(figsize=(14, 7))

# Line for real historical data
sns.lineplot(x='Ano', y='Internações Reais (Histórico)', data=df_plot.dropna(subset=['Internações Reais (Histórico)']),
             marker='o', label='Internações Reais (Histórico)', color='black', linewidth=3)

# Line for GBM predictions (historical and future)
sns.lineplot(x='Ano', y='Previsão GBM (Histórico e Futuro)', data=df_plot,
             marker='x', linestyle='--', label='Previsão GBM (Histórico e Futuro)', color='red', linewidth=2)

# Add confidence interval error bars for future predictions
plt.errorbar(x=future_years_for_errorbar,
             y=predictions_future_original_scale,
             yerr=margin_of_error_original_scale,
             fmt='s', capsize=5, color='blue', alpha=0.8, label='95% CI Futuro')

plt.xlabel('Ano', fontsize=14)
plt.ylabel('Número de Internações por Doenças Respiratórias', fontsize=14)
plt.xticks(df_plot['Ano'].unique(), rotation=45, fontsize=12)
plt.yticks(fontsize=12)
plt.grid(True)
plt.legend(fontsize=12)
plt.tight_layout()
plt.show()