# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e-oVqsrqKgsqD0EEc-cofEfRoCyJukcf
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Carregar o arquivo de poluição atmosférica, especificando a codificação e o delimitador
df_poluicao = pd.read_csv('/content/Poluicao_Atmosferica_osasco.csv', encoding='latin1', sep=';')

# Carregar o arquivo de internações por doenças respiratórias, especificando a codificação e o delimitador
df_internacoes = pd.read_csv('/content/Internacao_Doencas_Respiratorias.csv', encoding='latin1', sep=';')

print('Dados de Poluição Atmosférica (primeiras 5 linhas):')
display(df_poluicao.head())

print('\nInformações sobre os dados de Poluição Atmosférica:')
display(df_poluicao.info())

print('\nDados de Internações por Doenças Respiratórias (primeiras 5 linhas):')
display(df_internacoes.head())

print('\nInformações sobre os dados de Internações por Doenças Respiratórias:')
display(df_internacoes.info())

# Visualizar as primeiras linhas e informações de df_internacoes para garantir que a leitura foi completa
print('\nDados de Internações por Doenças Respiratórias (primeiras 5 linhas - completo):')
display(df_internacoes.head())

print('\nInformações sobre os dados de Internações por Doenças Respiratórias (completo):')
display(df_internacoes.info())

# Lista das colunas de meses em df_poluicao
month_columns = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho',
                 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro']

# Substituir vírgula por ponto e converter para numérico
for col in month_columns:
    df_poluicao[col] = df_poluicao[col].astype(str).str.replace(',', '.', regex=False).astype(float)

print('\nDados de Poluição Atmosférica após conversão de tipo (primeiras 5 linhas):')
display(df_poluicao.head())

print('\nInformações sobre os dados de Poluição Atmosférica após conversão de tipo:')
display(df_poluicao.info())

"""### 1.1 Agregação dos Dados de Poluição para Nível Anual

Como os dados de internação são anuais e não há levantamento mensal, vamos somar os valores mensais de poluição para obter um total anual para cada ano. Isso nos permitirá unificar os dados em uma granularidade anual para comparação.
"""

# As colunas de meses já foram convertidas para float em células anteriores
month_columns = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho',
                 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro']

# Criar uma cópia para evitar modificar o df_poluicao original se não for necessário
df_poluicao_anual = df_poluicao.copy()

# Calcular a soma anual dos poluentes
df_poluicao_anual['Poluicao_Anual_Total'] = df_poluicao_anual[month_columns].sum(axis=1)

# Selecionar apenas as colunas 'Ano' e 'Poluicao_Anual_Total'
df_poluicao_anual = df_poluicao_anual[['Ano', 'Poluicao_Anual_Total']]

print('df_poluicao_anual (primeiras 5 linhas):')
display(df_poluicao_anual.head())
print('\nInformações de df_poluicao_anual:')
display(df_poluicao_anual.info())

"""### 1.2 Unificação dos DataFrames Anuais

Agora que temos os dados de poluição agregados anualmente, podemos unificá-los com o DataFrame `df_internacoes` (que já possui dados anuais) usando a coluna 'Ano' como chave. Utilizaremos um `inner merge` para garantir que apenas os anos presentes em ambos os DataFrames sejam mantidos.
"""

# Realizar o merge dos DataFrames anuais
df_consolidado = pd.merge(df_poluicao_anual, df_internacoes, on='Ano', how='inner')

print('df_consolidado (primeiras 5 linhas após merge):')
display(df_consolidado.head())
print('\nInformações de df_consolidado:')
display(df_consolidado.info())

"""### 1.3 Filtragem de Anos Incompletos ou Não Pareados

Conforme solicitado, vamos excluir os anos 2008, 2009 e 2026, que podem ter dados incompletos ou não possuem pareamento completo em ambas as fontes, garantindo a qualidade do conjunto de dados para análise.
"""

years_to_exclude = [2008, 2009, 2026]

df_consolidado_filtered = df_consolidado[~df_consolidado['Ano'].isin(years_to_exclude)].reset_index(drop=True)

print('df_consolidado_filtered (primeiras 5 linhas após filtragem):')
display(df_consolidado_filtered.head(18))
print('\nInformações de df_consolidado_filtered:')
display(df_consolidado_filtered.info())

"""### 2. Normalização dos Dados Anuais

Agora que temos o `df_consolidado_filtered` com os dados anuais limpos, vamos aplicar o `MinMaxScaler` para normalizar as variáveis numéricas. Isso é importante para que os modelos de aprendizado de máquina não deem mais peso a variáveis com escalas maiores.
"""

from sklearn.preprocessing import MinMaxScaler

# Identificar colunas numéricas para normalização
# Excluímos 'Ano' pois é uma variável temporal/identificador e não deve ser escalada
numerical_cols_annual = [
    'Poluicao_Anual_Total',
    'Internações por doenças do aparelho respiratório',
    'Internações por doenças do trato respiratório superior',
    'Internações por doenças respiratórias'
]

# Criar uma cópia do DataFrame para armazenar os dados escalados
df_scaled_annual = df_consolidado_filtered.copy()

# Inicializar o MinMaxScaler
scaler_annual = MinMaxScaler()

# Aplicar o scaler às colunas selecionadas
df_scaled_annual[numerical_cols_annual] = scaler_annual.fit_transform(df_scaled_annual[numerical_cols_annual])

print('df_scaled_annual (primeiras 5 linhas após normalização):')
display(df_scaled_annual.head())
print('\nInformações de df_scaled_annual após normalização:')
display(df_scaled_annual.info())

"""### 3. Definição das Variáveis (X e y) e Divisão da Base de Dados

Agora que os dados estão normalizados, vamos definir nossas variáveis preditoras (`X`) e a variável alvo (`y`).

**Variável Alvo (y):** 'Internações por doenças respiratórias' (a última coluna, representando o total de internações respiratórias).

**Variáveis Preditivas (X):** Todas as outras colunas relevantes, excluindo a variável alvo e o 'Ano' (que é um identificador temporal, não uma feature preditiva direta nesta fase).
"""

# Definindo a variável alvo (y)
y = df_scaled_annual['Internações por doenças respiratórias']

# Definindo as variáveis preditoras (X)
# Excluímos 'Ano' e a coluna alvo
X = df_scaled_annual.drop(columns=['Ano', 'Internações por doenças respiratórias'])

print('Variáveis Preditivas (X) - primeiras 5 linhas:')
display(X.head())
print('\nInformações de X:')
display(X.info())

print('\nVariável Alvo (y) - primeiras 5 linhas:')
display(y.head())

"""### 4. Divisão da Base para Treinamento e Teste

Para avaliar a performance do modelo de forma justa, dividiremos os dados em conjuntos de treinamento e teste. Usaremos o `train_test_split` do scikit-learn, garantindo que o modelo seja avaliado em dados que não viu durante o treinamento.
"""

from sklearn.model_selection import train_test_split

# Dividir os dados em conjuntos de treinamento e teste (80% treino, 20% teste)
# Usamos random_state para reprodutibilidade
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Shape de X_train: {X_train.shape}")
print(f"Shape de X_test: {X_test.shape}")
print(f"Shape de y_train: {y_train.shape}")
print(f"Shape de y_test: {y_test.shape}")

"""### 5. Construção e Avaliação de Modelos Preditivos

Com os dados de treinamento e teste definidos, podemos agora construir e avaliar modelos de regressão para prever as internações por doenças respiratórias. Começaremos com o Random Forest Regressor, seguido por Gradient Boosting Machine (GBM) e Support Vector Regressor (SVR).
"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

# 5.1 Random Forest Regressor
print('**Treinando Random Forest Regressor...**')

# Inicializar o modelo Random Forest Regressor
# Usamos random_state para reprodutibilidade
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)

# Treinar o modelo
rf_model.fit(X_train, y_train)

# Fazer previsões no conjunto de teste
y_pred_rf = rf_model.predict(X_test)

# Avaliar o modelo
rmse_rf = np.sqrt(mean_squared_error(y_test, y_pred_rf))
mae_rf = mean_absolute_error(y_test, y_pred_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print(f"\n**Métricas de Avaliação do Random Forest Regressor:**")
print(f"RMSE: {rmse_rf:.4f}")
print(f"MAE: {mae_rf:.4f}")
print(f"R²: {r2_rf:.4f}")

from sklearn.ensemble import GradientBoostingRegressor

# 5.2 Gradient Boosting Machine (GBM) Regressor
print('\n**Treinando Gradient Boosting Machine (GBM) Regressor...**')

# Inicializar o modelo GBM Regressor
gbm_model = GradientBoostingRegressor(n_estimators=100, random_state=42)

# Treinar o modelo
gbm_model.fit(X_train, y_train)

# Fazer previsões no conjunto de teste
y_pred_gbm = gbm_model.predict(X_test)

# Avaliar o modelo
rmse_gbm = np.sqrt(mean_squared_error(y_test, y_pred_gbm))
mae_gbm = mean_absolute_error(y_test, y_pred_gbm)
r2_gbm = r2_score(y_test, y_pred_gbm)

print(f"\n**Métricas de Avaliação do Gradient Boosting Machine Regressor:**")
print(f"RMSE: {rmse_gbm:.4f}")
print(f"MAE: {mae_gbm:.4f}")
print(f"R²: {r2_gbm:.4f}")

from sklearn.svm import SVR

# 5.3 Support Vector Regressor (SVR)
print('\n**Treinando Support Vector Regressor (SVR)...**')

# Inicializar o modelo SVR
# Usamos o kernel 'rbf' (Radial Basis Function) como um bom ponto de partida
svr_model = SVR(kernel='rbf')

# Treinar o modelo
svr_model.fit(X_train, y_train)

# Fazer previsões no conjunto de teste
y_pred_svr = svr_model.predict(X_test)

# Avaliar o modelo
rmse_svr = np.sqrt(mean_squared_error(y_test, y_pred_svr))
mae_svr = mean_absolute_error(y_test, y_pred_svr)
r2_svr = r2_score(y_test, y_pred_svr)

print(f"\n**Métricas de Avaliação do Support Vector Regressor:**")
print(f"RMSE: {rmse_svr:.4f}")
print(f"MAE: {mae_svr:.4f}")
print(f"R²: {r2_svr:.4f}")

"""### 5.4 Comparativo dos Modelos"""

print("\n**Resumo Comparativo dos Modelos de Regressão:**")
print("---------------------------------------------------")

print(f"**Random Forest Regressor:**")
print(f"  RMSE: {rmse_rf:.4f}")
print(f"  MAE: {mae_rf:.4f}")
print(f"  R²: {r2_rf:.4f}")

print(f"\n**Gradient Boosting Machine Regressor (GBM):**")
print(f"  RMSE: {rmse_gbm:.4f}")
print(f"  MAE: {mae_gbm:.4f}")
print(f"  R²: {r2_gbm:.4f}")

print(f"\n**Support Vector Regressor (SVR):**")
print(f"  RMSE: {rmse_svr:.4f}")
print(f"  MAE: {mae_svr:.4f}")
print(f"  R²: {r2_svr:.4f}")

print("\nCom base nessas métricas, o modelo **Gradient Boosting Machine (GBM)** apresenta o melhor desempenho, com o menor RMSE e MAE, e o maior R² (mais próximo de 1). O Random Forest também teve um bom desempenho, enquanto o SVR não foi adequado para este problema com as configurações padrão.")

"""### 6. Previsão para Anos Futuros (2026 e 2027) e Margem de Confiança

Para realizar as previsões para os anos de 2026 e 2027, utilizaremos o modelo Gradient Boosting Machine (GBM), que se mostrou o mais eficaz. Como não temos dados futuros para todas as variáveis preditoras (poluição e outros tipos de internações), faremos as seguintes suposições:

*   **Poluição Atmosférica (Poluicao_Anual_Total):** Usaremos a média histórica dessa variável do conjunto de dados consolidado filtrado, já que não temos previsões futuras para a poluição.
*   **Internações por Doenças do Aparelho Respiratório (2026) e Internações por Doenças do Trato Respiratório Superior (2026):** Utilizaremos os valores disponíveis no `df_internacoes` para 2026 (72 e 3, respectivamente).
*   **Internações por Doenças do Aparelho Respiratório (2027) e Internações por Doenças do Trato Respiratório Superior (2027):** Para 2027, usaremos a média histórica dessas variáveis do conjunto de dados consolidado filtrado.

Após gerar as previsões, calcularemos uma margem de confiança aproximada de 95% com base nos resíduos do modelo no conjunto de teste.
"""

# Calcular médias para imputação (usando df_consolidado_filtered, que contém os anos de treinamento)
mean_poluicao = df_consolidado_filtered['Poluicao_Anual_Total'].mean()
mean_aparelho_respiratorio = df_consolidado_filtered['Internações por doenças do aparelho respiratório'].mean()
mean_trato_superior = df_consolidado_filtered['Internações por doenças do trato respiratório superior'].mean()

# Preparar os dados para as previsões de 2026 e 2027
data_for_prediction = pd.DataFrame({
    'Ano': [2026, 2027],
    'Poluicao_Anual_Total': [mean_poluicao, mean_poluicao],
    'Internações por doenças do aparelho respiratório': [72, mean_aparelho_respiratorio],
    'Internações por doenças do trato respiratório superior': [3, mean_trato_superior],
    'Internações por doenças respiratórias': [0, 0] # Placeholder para a coluna alvo para escalar corretamente
})

# Escalar os dados de previsão usando o mesmo scaler ajustado nos dados de treinamento
# numerical_cols_annual inclui a variável alvo, então escalamos o conjunto completo de colunas.
X_predict_scaled_full = scaler_annual.transform(data_for_prediction[numerical_cols_annual])

# Extrair apenas as colunas preditoras escaladas (as três primeiras)
X_predict_scaled = X_predict_scaled_full[:, :3]

# Gerar previsões usando o modelo GBM
y_pred_future_scaled = gbm_model.predict(X_predict_scaled)

# Inverter a transformação das previsões para a escala original
# Para fazer isso, precisamos criar um array 'dummy' que corresponda ao espaço de features original para o scaler
dummy_inverse_transform = np.zeros_like(X_predict_scaled_full)
dummy_inverse_transform[:, -1] = y_pred_future_scaled # Colocar as previsões na posição da coluna alvo

predictions_future_original_scale = scaler_annual.inverse_transform(dummy_inverse_transform)[:, -1]

# Exibir as previsões
print("Previsões para 2026 e 2027 (Internações por doenças respiratórias):")
print(f"2026: {predictions_future_original_scale[0]:.0f}")
print(f"2027: {predictions_future_original_scale[1]:.0f}")

# Calcular a margem de confiança
# Usando os resíduos do conjunto de teste para o modelo GBM
residuals_gbm = y_test - y_pred_gbm
std_residuals_scaled = np.std(residuals_gbm)

# Corrigir a obtenção do fator de escala para a variável alvo
# O fator de escala é a diferença entre o valor máximo e mínimo da variável alvo original
min_target_original = df_consolidado_filtered['Internações por doenças respiratórias'].min()
max_target_original = df_consolidado_filtered['Internações por doenças respiratórias'].max()
range_target_original = max_target_original - min_target_original

# Aproximar o intervalo de confiança de 95% usando o z-score (1.96 para distribuição normal)
z_score_95 = 1.96
margin_of_error_scaled = z_score_95 * std_residuals_scaled

# Converter a margem de erro para a escala original usando o range correto
margin_of_error_original_scale = margin_of_error_scaled * range_target_original

print("\nMargem de Confiança (95% CI) para as Previsões:")
print("------------------------------------------------")

lower_bound_2026 = predictions_future_original_scale[0] - margin_of_error_original_scale
upper_bound_2026 = predictions_future_original_scale[0] + margin_of_error_original_scale
print(f"2026: {predictions_future_original_scale[0]:.0f} (CI 95%: [{lower_bound_2026:.0f}, {upper_bound_2026:.0f}])")

lower_bound_2027 = predictions_future_original_scale[1] - margin_of_error_original_scale
upper_bound_2027 = predictions_future_original_scale[1] + margin_of_error_original_scale
print(f"2027: {predictions_future_original_scale[1]:.0f} (CI 95%: [{lower_bound_2027:.0f}, {upper_bound_2027:.0f}])")

print("\n**Nota sobre a Margem de Confiança:**")
print("Esta margem de confiança é uma aproximação baseada na distribuição dos resíduos do conjunto de teste do modelo GBM. Ela assume uma distribuição normal dos erros e homoscedasticidade. Para uma análise de incerteza mais robusta, métodos como bootstrap ou pacotes especializados para intervalos de predição em modelos de ensemble seriam mais apropriados.")

"""### 7. Visualização Temporal dos Dados Reais e Previsões do Modelo GBM

Vamos agora criar um gráfico temporal para visualizar a evolução das internações por doenças respiratórias, comparando os dados reais históricos com as previsões do modelo Gradient Boosting Machine (GBM) para o período histórico e estendendo para os anos de 2026 e 2027.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Criar um DataFrame para as previsões históricas do GBM nos dados de treinamento
y_pred_gbm_train = gbm_model.predict(X_train)

# Inverter a normalização para as previsões históricas do treinamento
dummy_inverse_transform_train = np.zeros_like(X_train.values) # Assegura que tenha as mesmas colunas
dummy_inverse_transform_train = np.insert(dummy_inverse_transform_train, dummy_inverse_transform_train.shape[1], y_pred_gbm_train, axis=1)
y_pred_gbm_train_original_scale = scaler_annual.inverse_transform(dummy_inverse_transform_train)[:, -1]

# Criar um DataFrame para as previsões históricas do GBM nos dados de teste
# y_pred_gbm já está na escala normalizada, precisamos inverter
dummy_inverse_transform_test = np.zeros_like(X_test.values) # Assegura que tenha as mesmas colunas
dummy_inverse_transform_test = np.insert(dummy_inverse_transform_test, dummy_inverse_transform_test.shape[1], y_pred_gbm, axis=1)
y_pred_gbm_test_original_scale = scaler_annual.inverse_transform(dummy_inverse_transform_test)[:, -1]

# Combinar os resultados históricos reais e preditos
# É importante manter a ordem dos anos
historical_data = df_consolidado_filtered.copy()
historical_data['Previsão GBM'] = np.nan # Placeholder

# Preencher as previsões para os anos correspondentes ao treinamento e teste
# Para X_train, mapear as previsões de volta aos índices originais do df_consolidado_filtered
for i, idx in enumerate(X_train.index):
    historical_data.loc[idx, 'Previsão GBM'] = y_pred_gbm_train_original_scale[i]

# Para X_test, mapear as previsões de volta aos índices originais do df_consolidado_filtered
for i, idx in enumerate(X_test.index):
    historical_data.loc[idx, 'Previsão GBM'] = y_pred_gbm_test_original_scale[i]

# Ordenar por ano para o gráfico
historical_data = historical_data.sort_values(by='Ano')

# Criar um DataFrame para as previsões futuras
future_predictions_df = pd.DataFrame({
    'Ano': [2026, 2027],
    'Internações por doenças respiratórias': predictions_future_original_scale,
    'Previsão GBM': predictions_future_original_scale
})

# Concatenar dados históricos e futuros para o gráfico da PREVISÃO TOTAL
combined_predictions_data = pd.concat([historical_data, future_predictions_df])

plt.figure(figsize=(14, 7))

# Linha para dados históricos reais - APENAS OS DADOS HISTÓRICOS REAIS
sns.lineplot(x='Ano', y='Internações por doenças respiratórias', data=historical_data, marker='o', label='Internações Reais (Histórico)', color='black', linewidth=3)

# Linha para a Previsão GBM (incluindo histórico e futuro)
sns.lineplot(x='Ano', y='Previsão GBM', data=combined_predictions_data, marker='x', linestyle='--', label='Previsão GBM (Histórico e Futuro)', color='red', linewidth=2)

# Adicionar o intervalo de confiança para as previsões futuras (apenas para os pontos de 2026 e 2027)
plt.errorbar(x=[2026, 2027],
             y=predictions_future_original_scale,
             yerr=margin_of_error_original_scale,
             fmt='s', capsize=5, color='blue', alpha=0.8, label='95% CI Futuro') # Increased alpha and changed color/marker

plt.xlabel('Ano', fontsize=14)
plt.ylabel('Número de Internações por Doenças Respiratórias', fontsize=14)
plt.xticks(combined_predictions_data['Ano'].unique(), rotation=45, fontsize = 12)
plt.yticks(fontsize = 12)
plt.grid(True)
plt.legend(fontsize=12)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Cria gráfico das duas séries temporais juntos Poluição x Internação
fig, ax1 = plt.subplots(figsize=(14, 7))

sns.lineplot(data=df_consolidado_filtered, x= 'Ano' , y = 'Internações por doenças respiratórias', ax = ax1, color = 'blue', label = 'Internações' )
ax1.set_ylabel('Internações', fontsize= 16)
ax1.set_xlabel('Ano', fontsize=16)
ax1.tick_params(axis='y', labelsize = 12)
ax1.tick_params(axis='x', labelsize = 12)
ax1.legend(loc='upper left', fontsize=12)

ax2 = ax1.twinx()

sns.lineplot(data=df_consolidado_filtered, x= 'Ano' , y = 'Poluicao_Anual_Total', color = 'red', ax = ax2, label = 'Poluição (Osasco)')
ax2.set_ylabel('Concentração do Poluente', fontsize=16)
ax2.tick_params(axis='y', labelsize = 12)
ax2.legend(loc='upper right', fontsize=12)

ax1.grid(True, alpha=0.3)
fig.tight_layout()

plt.show()

"""Para viabilizar a estratégia proposta e analisar o impacto do período da pandemia (2020-2024) como um 'ruído externo', vamos redefinir os conjuntos de treinamento e teste. O modelo será treinado exclusivamente com dados de 2010 a 2019 e, em seguida, será usado para prever as internações de 2020 a 2024. A análise dos resíduos (diferença entre o real e o previsto) nesse período de teste revelará o efeito não explicado pela poluição, presumivelmente devido à pandemia."""

# 1. Filtrar df_scaled_annual para os novos períodos de treinamento e teste
df_train_pandemic = df_scaled_annual[(df_scaled_annual['Ano'] >= 2010) & (df_scaled_annual['Ano'] <= 2019)].copy()
df_test_pandemic = df_scaled_annual[(df_scaled_annual['Ano'] >= 2020) & (df_scaled_annual['Ano'] <= 2024)].copy()

print('Dados de Treinamento (2010-2019) - primeiras 5 linhas:')
display(df_train_pandemic.head(10))
print(f'Shape df_train_pandemic: {df_train_pandemic.shape}')

print('\nDados de Teste (2020-2024) - primeiras 5 linhas:')
display(df_test_pandemic.head())
print(f'Shape df_test_pandemic: {df_test_pandemic.shape}')

# 2. Redefinir X e y para os novos conjuntos
X_train_pandemic = df_train_pandemic.drop(columns=['Ano', 'Internações por doenças respiratórias'])
y_train_pandemic = df_train_pandemic['Internações por doenças respiratórias']

X_test_pandemic = df_test_pandemic.drop(columns=['Ano', 'Internações por doenças respiratórias'])
y_test_pandemic = df_test_pandemic['Internações por doenças respiratórias']

print('\nShape de X_train_pandemic: {X_train_pandemic.shape}')
print('Shape de y_train_pandemic: {y_train_pandemic.shape}')
print('Shape de X_test_pandemic: {X_test_pandemic.shape}')
print('Shape de y_test_pandemic: {y_test_pandemic.shape}')

"""### 9. Retreinamento do Modelo GBM e Análise de Resíduos (Pandemia)

Com os novos conjuntos de dados, vamos retreinar o modelo GBM e, em seguida, calcular e visualizar os resíduos para o período de 2020-2024. Isso nos permitirá observar o 'efeito líquido do ruído externo' da pandemia, como proposto.
"""

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Retreinar o modelo GBM Regressor com os dados pré-pandemia (2010-2019)
print('**Retreinando Gradient Boosting Machine (GBM) Regressor com dados 2010-2019...**')
gbm_model_pandemic = GradientBoostingRegressor(n_estimators=100, random_state=42)
gbm_model_pandemic.fit(X_train_pandemic, y_train_pandemic)

# Fazer previsões no novo conjunto de teste (2020-2024)
y_pred_gbm_pandemic = gbm_model_pandemic.predict(X_test_pandemic)

# 3. Calcular métricas de avaliação para o período de teste (2020-2024)
rmse_gbm_pandemic = np.sqrt(mean_squared_error(y_test_pandemic, y_pred_gbm_pandemic))
mae_gbm_pandemic = mean_absolute_error(y_test_pandemic, y_pred_gbm_pandemic)
r2_gbm_pandemic = r2_score(y_test_pandemic, y_pred_gbm_pandemic)

print(f"\n**Métricas de Avaliação do GBM (Teste 2020-2024):**")
print(f"RMSE: {rmse_gbm_pandemic:.4f}")
print(f"MAE: {mae_gbm_pandemic:.4f}")
print(f"R²: {r2_gbm_pandemic:.4f}")

# Inverter a normalização para as previsões e valores reais para análise de resíduos
dummy_inverse_transform_real = np.zeros_like(X_test_pandemic.values)
dummy_inverse_transform_real = np.insert(dummy_inverse_transform_real, dummy_inverse_transform_real.shape[1], y_test_pandemic, axis=1)
y_test_pandemic_original_scale = scaler_annual.inverse_transform(dummy_inverse_transform_real)[:, -1]

dummy_inverse_transform_pred = np.zeros_like(X_test_pandemic.values)
dummy_inverse_transform_pred = np.insert(dummy_inverse_transform_pred, dummy_inverse_transform_pred.shape[1], y_pred_gbm_pandemic, axis=1)
y_pred_gbm_pandemic_original_scale = scaler_annual.inverse_transform(dummy_inverse_transform_pred)[:, -1]

# Calcular resíduos em escala original
residuals_pandemic = y_test_pandemic_original_scale - y_pred_gbm_pandemic_original_scale

# Adicionar resíduos ao DataFrame de teste para visualização
df_test_pandemic['Internações Reais'] = y_test_pandemic_original_scale
df_test_pandemic['Previsão GBM'] = y_pred_gbm_pandemic_original_scale
df_test_pandemic['Resíduos'] = residuals_pandemic

print('\nAnálise de Resíduos (2020-2024):')
display(df_test_pandemic[['Ano', 'Internações Reais', 'Previsão GBM', 'Resíduos']])

# Visualizar Resíduos ao longo do tempo
plt.figure(figsize=(12, 6))
sns.lineplot(x='Ano', y='Resíduos', data=df_test_pandemic, marker='o', color='purple')
plt.axhline(0, color='red', linestyle='--', linewidth=1, label='Resíduo Zero')

plt.xlabel('Ano', fontsize = 12)
plt.ylabel('Resíduos (Real - Previsto)', fontsize=12)

plt.xticks(df_test_pandemic['Ano'], fontsize=12)
plt.yticks(fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(fontsize=12)
plt.tight_layout()
plt.show()

"""### 10. Visualização Comparativa: Real vs. Previsão GBM (Com Destaque ao Período da Pandemia)

Para consolidar a análise, vamos plotar os dados reais e as previsões do modelo GBM para todo o período (2010-2024), destacando o período da pandemia para ilustrar visualmente a discrepância entre o esperado e o observado.
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Preparar dados para o gráfico de comparação
# Inverter a normalização para os dados de treinamento (2010-2019)
y_pred_gbm_train_pandemic = gbm_model_pandemic.predict(X_train_pandemic)

dummy_inverse_transform_train_real = np.zeros_like(X_train_pandemic.values)
dummy_inverse_transform_train_real = np.insert(dummy_inverse_transform_train_real, dummy_inverse_transform_train_real.shape[1], y_train_pandemic, axis=1)
y_train_pandemic_original_scale = scaler_annual.inverse_transform(dummy_inverse_transform_train_real)[:, -1]

dummy_inverse_transform_train_pred = np.zeros_like(X_train_pandemic.values)
dummy_inverse_transform_train_pred = np.insert(dummy_inverse_transform_train_pred, dummy_inverse_transform_train_pred.shape[1], y_pred_gbm_train_pandemic, axis=1)
y_pred_gbm_train_original_scale = scaler_annual.inverse_transform(dummy_inverse_transform_train_pred)[:, -1]

# Criar DataFrames para facilitar a plotagem
df_plot_train = pd.DataFrame({
    'Ano': df_train_pandemic['Ano'],
    'Internações Reais': y_train_pandemic_original_scale,
    'Previsão GBM': y_pred_gbm_train_original_scale
})

df_plot_test = pd.DataFrame({
    'Ano': df_test_pandemic['Ano'],
    'Internações Reais': y_test_pandemic_original_scale,
    'Previsão GBM': y_pred_gbm_pandemic_original_scale
})

# Concatenar para ter um único DataFrame para o gráfico
df_combined_plot = pd.concat([df_plot_train, df_plot_test]).sort_values(by='Ano').reset_index(drop=True)

plt.figure(figsize=(14, 7))

sns.lineplot(x='Ano', y='Internações Reais', data=df_combined_plot, marker='o', label='Internações Reais', color='black', linewidth=2)
sns.lineplot(x='Ano', y='Previsão GBM', data=df_combined_plot, marker='x', linestyle='--', label='Previsão GBM (Modelo Pré-Pandemia)', color='red', linewidth=2)

# Destacar o período da pandemia (2020-2021) com uma área sombreada
plt.axvspan(2019, 2021, color='gray', alpha=0.3, label='Período da Pandemia (2020-2021)')

plt.xlabel('Ano', fontsize=14)
plt.ylabel('Número de Internações por Doenças Respiratórias', fontsize=14)
plt.xticks(df_combined_plot['Ano'].unique(), rotation=45, fontsize=14)
plt.yticks(fontsize=14)

plt.grid(True, linestyle='--', alpha=0.7)
plt.legend(fontsize=14)
plt.tight_layout()
plt.show()