# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fcNW8aWlr83hkD0gfpT1C_TYjR2bEsH7
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Load the CSV file into a pandas DataFrame, specifying 'latin1' encoding
df = pd.read_csv('/content/Consolidado_Internacao_Poluicao_rev1.csv', encoding='latin1', sep=';')

# Display the first 5 rows of the DataFrame
display(df.head(18))

from sklearn.preprocessing import MinMaxScaler

# Identify columns to normalize
columns_to_normalize = [
    'Poluicao_Anual_Total',
    'Internações por doenças do aparelho respiratório',
    'Internações por doenças do trato respiratório superior',
    'Internações por doenças respiratórias'
]

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Apply Min-Max scaling to the selected columns
df_normalized = df.copy()
df_normalized[columns_to_normalize] = scaler.fit_transform(df[columns_to_normalize])

# Display the head of the DataFrame with normalized data
print("DataFrame com dados normalizados:")
display(df_normalized.head())

# Display descriptive statistics for normalized columns to verify
print("Estatísticas descritivas das colunas normalizadas:")
display(df_normalized[columns_to_normalize].describe())

# Variável alvo (y)
y = df_normalized['Internações por doenças respiratórias']

# Variáveis preditoras (X): Todas as outras colunas relevantes, excluindo 'Ano', 'Unnamed: 0' e a variável alvo
X = df_normalized.drop(columns=['Ano', 'Internações por doenças respiratórias', 'Unnamed: 0'])


print("Primeiras 5 linhas das variáveis preditoras (X):")
display(X.head())

print("Primeiras 5 linhas da variável alvo (y):")
display(y.head())

df_normalized['Pandemia'] = df_normalized['Ano'].apply(lambda x: 1 if x in [2020, 2021] else 0)

# Display the head of the DataFrame with the new 'Pandemia' column
print("DataFrame com a coluna 'Pandemia':")
display(df_normalized.head(18))

"""### Divisão da Base de Dados para Treinamento e Teste
Para avaliar o desempenho do nosso modelo de forma robusta, dividiremos os dados normalizados em conjuntos de treinamento e teste. Isso garante que o modelo seja treinado com uma parte dos dados e avaliado em dados que ele não viu durante o treinamento, fornecendo uma estimativa mais realista de sua capacidade de generalização.
"""

from sklearn.model_selection import train_test_split

# Dividir os dados em conjuntos de treinamento e teste
# Usamos test_size=0.2, o que significa que 20% dos dados serão usados para teste.
# random_state é usado para garantir a reprodutibilidade da divisão.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Shape de X_train: {X_train.shape}")
print(f"Shape de X_test: {X_test.shape}")
print(f"Shape de y_train: {y_train.shape}")
print(f"Shape de y_test: {y_test.shape}")

"""### Construção e Avaliação de Modelos Preditivos
Com os dados de treinamento e teste definidos, podemos agora construir e avaliar modelos de regressão para prever as internações por doenças respiratórias. Começaremos com o Random Forest Regressor, seguido por Gradient Boosting Machine (GBM) e Support Vector Regressor (SVR).

#### Random Forest Regressor
O Random Forest é um algoritmo de aprendizado de máquina que constrói múltiplas árvores de decisão e as mescla para obter uma previsão mais precisa e estável. É eficaz para lidar com não linearidades e interações complexas nos dados.
"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Inicializar e treinar o modelo Random Forest Regressor
# random_state é usado para garantir a reprodutibilidade
rf_model = RandomForestRegressor(random_state=42)
rf_model.fit(X_train, y_train)

# Fazer previsões no conjunto de teste
y_pred_rf = rf_model.predict(X_test)

# Avaliar o desempenho do modelo
mae_rf = mean_absolute_error(y_test, y_pred_rf)
mse_rf = mean_squared_error(y_test, y_pred_rf)
rmse_rf = np.sqrt(mse_rf)
r2_rf = r2_score(y_test, y_pred_rf)

print("Desempenho do Random Forest Regressor:")
print(f"MAE: {mae_rf:.4f}")
print(f"MSE: {mse_rf:.4f}")
print(f"RMSE: {rmse_rf:.4f}")
print(f"R-squared: {r2_rf:.4f}")

"""#### Gradient Boosting Machine (GBM)
O Gradient Boosting Machine é outro algoritmo de ensemble que constrói um modelo preditivo de forma sequencial, onde cada nova árvore tenta corrigir os erros das árvores anteriores. Ele é conhecido por sua alta precisão.
"""

from sklearn.ensemble import GradientBoostingRegressor

# Inicializar e treinar o modelo Gradient Boosting Regressor
# random_state é usado para garantir a reprodutibilidade
gbm_model = GradientBoostingRegressor(random_state=42)
gbm_model.fit(X_train, y_train)

# Fazer previsões no conjunto de teste
y_pred_gbm = gbm_model.predict(X_test)

# Avaliar o desempenho do modelo
mae_gbm = mean_absolute_error(y_test, y_pred_gbm)
mse_gbm = mean_squared_error(y_test, y_pred_gbm)
rmse_gbm = np.sqrt(mse_gbm)
r2_gbm = r2_score(y_test, y_pred_gbm)

print("Desempenho do Gradient Boosting Machine:")
print(f"MAE: {mae_gbm:.4f}")
print(f"MSE: {mse_gbm:.4f}")
print(f"RMSE: {rmse_gbm:.4f}")
print(f"R-squared: {r2_gbm:.4f}")

"""#### Support Vector Regressor (SVR)
O Support Vector Regressor (SVR) é uma adaptação dos Support Vector Machines (SVMs) para tarefas de regressão. Ele busca encontrar uma função que desvie por no máximo ε (epsilon) das previsões reais para todos os dados de treinamento, tentando, ao mesmo tempo, ser o mais plana possível.
"""

from sklearn.svm import SVR

# Inicializar e treinar o modelo Support Vector Regressor
# Usaremos um kernel linear como ponto de partida
svr_model = SVR(kernel='linear')
svr_model.fit(X_train, y_train)

# Fazer previsões no conjunto de teste
y_pred_svr = svr_model.predict(X_test)

# Avaliar o desempenho do modelo
mae_svr = mean_absolute_error(y_test, y_pred_svr)
mse_svr = mean_squared_error(y_test, y_pred_svr)
rmse_svr = np.sqrt(mse_svr)
r2_svr = r2_score(y_test, y_pred_svr)

print("Desempenho do Support Vector Regressor (SVR):")
print(f"MAE: {mae_svr:.4f}")
print(f"MSE: {mse_svr:.4f}")
print(f"RMSE: {rmse_svr:.4f}")
print(f"R-squared: {r2_svr:.4f}")

"""### Resumo dos Resultados dos Modelos
Vamos consolidar os resultados de desempenho de todos os modelos para facilitar a comparação.
"""

import pandas as pd

results = pd.DataFrame({
    'Modelo': ['Random Forest', 'Gradient Boosting', 'Support Vector Regressor'],
    'MAE': [mae_rf, mae_gbm, mae_svr],
    'MSE': [mse_rf, mse_gbm, mse_svr],
    'RMSE': [rmse_rf, rmse_gbm, rmse_svr],
    'R-squared': [r2_rf, r2_gbm, r2_svr]
})

print("Comparativo de Desempenho dos Modelos:")
display(results.round(4))

# Identificar o melhor modelo com base no R-squared
best_model_r2 = results.loc[results['R-squared'].idxmax()]
print(f"\nO melhor modelo com base no R-squared é o {best_model_r2['Modelo']} com R-squared de {best_model_r2['R-squared']:.4f}.")

# Identificar o melhor modelo com base no menor RMSE
best_model_rmse = results.loc[results['RMSE'].idxmin()]
print(f"O melhor modelo com base no menor RMSE é o {best_model_rmse['Modelo']} com RMSE de {best_model_rmse['RMSE']:.4f}.")

"""### Visualização do Desempenho do SVR: Valores Reais vs. Valores Preditos

Agora que identificamos o Support Vector Regressor (SVR) como o melhor modelo, vamos visualizar seu desempenho comparando os valores reais (`y_test`) com os valores preditos (`y_pred_svr`). Isso nos dará uma compreensão visual de quão bem o modelo se ajusta aos dados históricos, especialmente durante os anos de pandemia (2020-2021).
"""

import matplotlib.pyplot as plt
import seaborn as sns

# Set global font size for all text elements to 12
plt.rcParams.update({'font.size': 12})

# Criar um DataFrame para facilitar a plotagem
plot_df = pd.DataFrame({
    'Ano': df_normalized.loc[X_test.index, 'Ano'], # Retrieve 'Ano' using X_test's index from the original normalized DataFrame
    'Real': y_test,
    'Predito': y_pred_svr
})

# Ordenar por ano para garantir que a linha do tempo esteja correta
plot_df = plot_df.sort_values(by='Ano').reset_index(drop=True)

plt.figure(figsize=(12, 6))
sns.lineplot(x='Ano', y='Real', data=plot_df, label='Valores Reais', marker='o')
sns.lineplot(x='Ano', y='Predito', data=plot_df, label='Valores Preditos (SVR)', marker='x')

plt.xlabel('Ano')
plt.ylabel('Internações por Doenças Respiratórias (Normalizado)')
plt.xticks(plot_df['Ano'].unique()) # Garante que todos os anos sejam exibidos no eixo X
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend()
plt.show()

"""### Previsão para Anos Futuros (2026 e 2027) com Margem de Confiança

Agora, vamos usar o modelo SVR, identificado como o mais eficaz, para fazer previsões para os anos de 2026 e 2027. Para isso, faremos uma suposição sobre os valores das variáveis preditoras para esses anos futuros.

**Suposição:** Para as variáveis 'Poluicao_Anual_Total', 'Internações por doenças do aparelho respiratório' e 'Internações por doenças do trato respiratório superior', utilizaremos a média dos seus valores normalizados observados nos anos *não-pandêmicos* da base de dados. A variável 'Pandemia' será definida como 0 para 2026 e 2027. Em um cenário real, estas variáveis precisariam ser projetadas ou fornecidas por especialistas.

Após a previsão, calcularemos uma margem de confiança de 95% baseada nos resíduos do modelo no conjunto de teste para dar uma estimativa da incerteza das previsões.
"""

import numpy as np
from scipy import stats

# --- 1. Preparar os dados para os anos futuros (2026 e 2027) ---

# Identificar as colunas de features que foram usadas em X (excluindo 'Ano' e 'Unnamed: 0')
# e que não são a variável 'Pandemia' para calcular a média.
features_for_mean_calc = X.columns.drop('Pandemia')

# Obter as linhas de df_normalized que correspondem a anos não-pandêmicos (Pandemia == 0)
non_pandemic_df_normalized = df_normalized[df_normalized['Pandemia'] == 0]

# Calcular a média dessas features para os anos não-pandêmicos
mean_feature_values_normalized = non_pandemic_df_normalized[features_for_mean_calc].mean()

# Criar um DataFrame para os anos futuros
future_years_list = [2026, 2027]
X_future = pd.DataFrame([mean_feature_values_normalized] * len(future_years_list), columns=features_for_mean_calc)
X_future['Pandemia'] = 0 # Definir 'Pandemia' como 0 para os anos futuros
X_future['Ano'] = future_years_list # Adicionar 'Ano' para identificação

# Garantir que a ordem das colunas seja a mesma que X_train para o modelo SVR
X_future = X_future[X_train.columns]

print("Dados de entrada para previsão (X_future):")
display(X_future)

# --- 2. Fazer as previsões com o modelo SVR ---
y_pred_future = svr_model.predict(X_future)

# --- 3. Calcular a margem de confiança (95%) ---

# Calcular os resíduos do conjunto de teste
residuals = y_test - y_pred_svr

# Calcular o desvio padrão dos resíduos
std_residuals = residuals.std()

# Para 95% de confiança, o valor Z-score é aproximadamente 1.96
z_score = 1.96 # Usando z-score para uma aproximação de intervalo de confiança

# Calcular a margem de erro
margin_of_error = z_score * std_residuals

# Calcular os limites inferior e superior do intervalo de confiança para as previsões futuras
lower_bound_future = y_pred_future - margin_of_error
upper_bound_future = y_pred_future + margin_of_error

# --- Inverse transform the predictions and confidence bounds to original scale ---
# Find the index of the target variable in columns_to_normalize
target_col_index = columns_to_normalize.index('Internações por doenças respiratórias')

# Prepare an array for inverse transformation of predictions and bounds
y_pred_future_original_scale = scaler.inverse_transform(np.c_[np.zeros((len(y_pred_future), target_col_index)), y_pred_future.reshape(-1, 1), np.zeros((len(y_pred_future), len(columns_to_normalize) - target_col_index - 1))])[:, target_col_index]
lower_bound_future_original_scale = scaler.inverse_transform(np.c_[np.zeros((len(lower_bound_future), target_col_index)), lower_bound_future.reshape(-1, 1), np.zeros((len(lower_bound_future), len(columns_to_normalize) - target_col_index - 1))])[:, target_col_index]
upper_bound_future_original_scale = scaler.inverse_transform(np.c_[np.zeros((len(upper_bound_future), target_col_index)), upper_bound_future.reshape(-1, 1), np.zeros((len(upper_bound_future), len(columns_to_normalize) - target_col_index - 1))])[:, target_col_index]

# Inverse transform std_residuals and margin_of_error
temp_std_residuals_array = np.zeros((1, len(columns_to_normalize)))
temp_std_residuals_array[0, target_col_index] = std_residuals
std_residuals_original_scale = scaler.inverse_transform(temp_std_residuals_array)[0, target_col_index]

temp_margin_of_error_array = np.zeros((1, len(columns_to_normalize)))
temp_margin_of_error_array[0, target_col_index] = margin_of_error
margin_of_error_original_scale = scaler.inverse_transform(temp_margin_of_error_array)[0, target_col_index]


# --- 4. Exibir os resultados --- (usando os valores na escala original)
results_future = pd.DataFrame({
    'Ano': future_years_list,
    'Previsão SVR (Original)': y_pred_future_original_scale.round(2),
    'Limite Inferior (95% CI Original)': lower_bound_future_original_scale.round(2),
    'Limite Superior (95% CI Original)': upper_bound_future_original_scale.round(2)
})

print("\nPrevisões de Internações por Doenças Respiratórias (SVR) para 2026 e 2027 com 95% CI (Valores Originais):")
display(results_future)

print(f"\nDesvio Padrão dos Resíduos do SVR no Teste (Original): {std_residuals_original_scale:.2f}")
print(f"Margem de Erro (95% CI Original): +/- {margin_of_error_original_scale:.2f}")

"""### Visualização Temporal dos Dados Reais e Previsões do Modelo SVR

Para ter uma visão abrangente do desempenho do modelo e de suas previsões futuras, vamos criar um gráfico de linha que mostra os dados históricos reais, as previsões do SVR para o período histórico e as previsões estendidas para 2026 e 2027.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# Set global font size for all text elements to 12
plt.rcParams.update({'font.size': 12})

# --- Inverse transform the data to original scale ---
# Find the index of the target variable in columns_to_normalize
target_col_index = columns_to_normalize.index('Internações por doenças respiratórias')

# Prepare an array to inverse transform for the target variable. It needs to be 2D.
# We need to create a dummy array with zeros for other features, and place the normalized target
# at its correct position to use the scaler's inverse_transform correctly.

# Inverse transform y (original actual values)
# The 'y' Series was created from 'df_normalized', so it is already normalized.
y_original_scale = scaler.inverse_transform(np.c_[np.zeros((len(y), target_col_index)), y.values.reshape(-1, 1), np.zeros((len(y), len(columns_to_normalize) - target_col_index - 1))])[:, target_col_index]

# Inverse transform y_pred_all_historical
y_pred_all_historical_original_scale = scaler.inverse_transform(np.c_[np.zeros((len(y_pred_all_historical), target_col_index)), y_pred_all_historical.reshape(-1, 1), np.zeros((len(y_pred_all_historical), len(columns_to_normalize) - target_col_index - 1))])[:, target_col_index]

# Inverse transform y_pred_future, lower_bound_future, upper_bound_future
y_pred_future_original_scale = scaler.inverse_transform(np.c_[np.zeros((len(y_pred_future), target_col_index)), y_pred_future.reshape(-1, 1), np.zeros((len(y_pred_future), len(columns_to_normalize) - target_col_index - 1))])[:, target_col_index]
lower_bound_future_original_scale = scaler.inverse_transform(np.c_[np.zeros((len(lower_bound_future), target_col_index)), lower_bound_future.reshape(-1, 1), np.zeros((len(lower_bound_future), len(columns_to_normalize) - target_col_index - 1))])[:, target_col_index]
upper_bound_future_original_scale = scaler.inverse_transform(np.c_[np.zeros((len(upper_bound_future), target_col_index)), upper_bound_future.reshape(-1, 1), np.zeros((len(upper_bound_future), len(columns_to_normalize) - target_col_index - 1))])[:, target_col_index]

# --- Step 1: Make predictions for ALL historical data ---

# Create a DataFrame for all historical real and predicted values using original scale
historical_plot_df_full = pd.DataFrame({
    'Ano': df_normalized['Ano'], # Ano is not scaled
    'Real': y_original_scale,
    'Predito': y_pred_all_historical_original_scale
})

# Prepare future data (from results_future generated previously) using original scale
future_plot_df = pd.DataFrame({
    'Ano': future_years_list,
    'Predito': y_pred_future_original_scale,
    'Lower_CI': lower_bound_future_original_scale,
    'Upper_CI': upper_bound_future_original_scale
})

# Combine historical and future predictions
# For future years, 'Real' will be NaN as there are no actual values yet
combined_predictions = pd.concat([
    historical_plot_df_full.assign(source='Histórico'),
    future_plot_df.assign(Real=np.nan, source='Futuro')
], ignore_index=True)

# Sort by year to ensure correct line plotting
combined_predictions = combined_predictions.sort_values(by='Ano').reset_index(drop=True)

plt.figure(figsize=(14, 7))

# Plot Historical Real Values
sns.lineplot(x='Ano', y='Real', data=combined_predictions[combined_predictions['source'] == 'Histórico'],
             marker='o', label='Valores Reais Históricos', color='black') # Changed color to black

# Combine historical and future SVR predictions for a single line
combined_svr_predictions = combined_predictions[combined_predictions['source'].isin(['Histórico', 'Futuro'])].copy()
# For the combined line, only show 'Predito' for both historical and future
# Use 'Ano' from combined_svr_predictions to get correct x-axis values.
# We need to ensure that the 'Predito' values are ordered correctly.
combined_svr_predictions = combined_svr_predictions.sort_values(by='Ano').reset_index(drop=True)

sns.lineplot(x='Ano', y='Predito', data=combined_svr_predictions,
             marker='x', label='Previsão SVR (Histórico e Futuro)', color='red', linestyle='-.') # Unified label and color

# Plot Future Confidence Interval (this remains the same)
plt.fill_between(
    future_plot_df['Ano'],
    future_plot_df['Lower_CI'],
    future_plot_df['Upper_CI'],
    color='red', alpha=0.1, label='95% Intervalo de Confiança (Futuro)'
)

plt.title('Dados Reais vs. Predições SVR (Histórico e Futuro)', fontsize=12)
plt.xlabel('Ano', fontsize=12)
plt.ylabel('Internações por Doenças Respiratórias (Valores Originais)', fontsize=12)
plt.xticks(combined_predictions['Ano'].unique())
plt.grid(True, linestyle='--', alpha=0.7)
plt.legend(fontsize=12)
plt.tight_layout()
plt.show()